(load "package")
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")))
(package-initialize)
(require 'ido)
;; slime
(require 'slime)
(slime-setup '(slime-asdf slime-repl slime-scratch slime-presentations slime-media))
(require 'slime-autoloads)
(add-to-list 'slime-contribs 'slime-fancy)
;; end slime
(add-to-list 'load-path (expand-file-name "~/.emacs.d/neotree"))
(require 'neotree)
(global-set-key [f8] 'neotree-toggle)
(global-set-key [f7] 'neotree-hidden-file-toggle)

(add-to-list 'load-path (expand-file-name "~/.emacs.d/emacs-livedown"))
(require 'livedown)
(add-to-list 'load-path (expand-file-name "~/.emacs.d/go-mode.el"))
(autoload 'go-mode "go-mode" t nil)
(add-to-list 'load-path (expand-file-name "~/.emacs.d/gocode/emacs"))
(require 'go-autocomplete)
(require 'auto-complete-config)
(ac-config-default)
(add-to-list 'load-path (expand-file-name "~/.emacs.d/goflymake"))
(require 'go-flymake)
(require 'go-flycheck)
(add-to-list 'load-path (expand-file-name "~/.emacs.d/my"))
(require 'hooks)
(require 'settings)
