(custom-set-variables
 '(custom-enabled-themes (wombat))
 '(inferior-lisp-program "sbcl" t)
 '(package-selected-packages
   '(flycheck markdown-mode swank-cdt auto-complete paredit slime))
 '(slime-auto-select-connection always)
 '(slime-auto-start 'always)
 '(livedown-autostart nil)
 '(livedown-open t)
 '(livedown-port 1337)
 '(livedown-browser nil)
 '(use-dialog-box nil)
 '(redisplay-dont-pause t)
 '(ring-bell-function 'ignore)
 '(tooltip-mode -1)
 '(menu-bar-mode -1)
 '(neo-smart-open t)
 '(ido-mode t)
 '(slime-net-coding-system 'utf-8-unix)
 '(shell-file-name "/bin/zsh")
 '(explicit-shell-file-name "/bin/zsh")
 '(display-line-numbers t)
 '(display-time-24hr-format t)
 '(display-time-mode t)
 '(ident-tab-mode nil)
 '(tab-width 4)
 '(standart-indent 4)
 '(lisp-body-ident 2)
 '(sh-basic-offset 2)
 '(sh-indentation 2)
 '(scroll-step 1)
 '(scrooll-margin 4)
 '(x-select-enable-clipboard t)
 '(search-highlight t)
 '(query-replace-highlight)
 )

(custom-set-faces
 )

(defalias 'yes-or-no-p 'y-or-n-p)

(cua-mode)
(show-paren-mode)

(provide 'settings)
